require("functions.ParseName")
require("functions.GenerateUnitSpawns")
require("functions.SpawnAttack")
require("events.SpawnPollution")
require("events.Teleport")
require("events.Paranoia")
require("events.Attack")